esphome:
  name: test
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: False

external_components:
  - source: components

i2c:
  sda: GPIO4
  scl: GPIO5

i2c_eeprom:
  - id: my_eeprom
    size: 16KB
    on_setup:
      then:
        - lambda: |-
            uint8_t prev_state;
            my_eeprom->get(0x0001, &prev_state);
            ESP_LOGW("eeprom","INIT Read: 0x%02X ", prev_state);

switch:
  - platform: gpio
    id: test
    pin:
      number: GPIO15
    on_turn_on:
      - lambda: |-
          my_eeprom->put(0x0001, 0b1); 

          uint8_t read_byte;
          my_eeprom->get(0x0001, &read_byte);
          ESP_LOGD("eeprom","Read: 0x%02X ", read_byte);
    on_turn_off:
      - lambda: |-
          my_eeprom->put(0x0001, 0b0);

          uint8_t read_byte;
          my_eeprom->get(0x0001, &read_byte);
          ESP_LOGD("eeprom","Read: 0x%02X ", read_byte);
