name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check conventional commits
        uses: webiny/action-conventional-commits@v1.3.0

      - name: Setup & build
        uses: esphome/build-action@v1
        with:
          yaml_file: example.yaml
